#ifndef __LINUX_PKT_SCH_THEATERQ_H
#define __LINUX_PKT_SCH_THEATERQ_H

#include <uapi/linux/pkt_sched.h>

enum {
    THEATERQ_STAGE_UNSPEC,
    THEATERQ_STAGE_INIT,
    THEATERQ_STAGE_LOAD,
    THEATERQ_STAGE_RUN,
    THEATERQ_STAGE_FINISH,
    __THEATERQ_STAGE_MAX,
};
#define THEATERQ_STAGE_MAX (__THEATERQ_STAGE_MAX - 1)

enum {
    THEATERQ_CONT_UNSPEC,
    THEATERQ_CONT_HOLD,
    THEATERQ_CONT_LOOP,
    THEATERQ_CONT_CLEAR,
    __THEATERQ_CONT_MAX,
};
#define THEATERQ_CONT_MAX (__THEATERQ_CONT_MAX - 1)

enum {
    TCA_THEATERQ_UNSPEC,
    TCA_THEATERQ_PAD,
    TCA_THEATERQ_MODE,
    TCA_THEATERQ_PRNG_SEED,
    TCA_THEATERQ_PKT_OVERHEAD,
    __TCA_THEATERQ_MAX,
};
#define TCA_THEATERQ_MAX (__TCA_THEATERQ_MAX - 1)

#endif //__LINUX_PKT_SCH_THEATERQ_H
