#ifndef __LINUX_PKT_SCH_THEATERQ_H
#define __LINUX_PKT_SCH_THEATERQ_H

#include <uapi/linux/pkt_sched.h>

enum {
    THEATERQ_STAGE_UNSPEC,
    THEATERQ_STAGE_LOAD,
    THEATERQ_STAGE_RUN,
    THEATERQ_STAGE_FINISH,
    __THEATERQ_STAGE_MAX,
};
#define THEATERQ_STAGE_MAX (__THEATERQ_STAGE_MAX - 1)


enum {
    TCA_THEATERQ_UNSPEC,
    TCA_THEATERQ_PAD,
    TCA_THEATERQ_MODE,
    __TCA_THEATERQ_MAX,
};
#define TCA_THEATERQ_MAX (__TCA_THEATERQ_MAX - 1)

#endif //__LINUX_PKT_SCH_THEATERQ_H